# Generated by Django 4.0.6 on 2022-07-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_remove_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
