# Generated by Django 4.0.5 on 2022-06-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплена?')),
                ('preview', models.ImageField(blank=True, upload_to='notes_preview/%Y-%m-%d/', verbose_name='Превью')),
                ('body', models.TextField(blank=True, verbose_name='Наполнение')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалена?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена в')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'ordering': ('-created_at',),
            },
        ),
    ]
