# Generated by Django 4.0.6 on 2022-07-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='preview',
        ),
    ]
