# Generated by Django 4.0.6 on 2022-07-13 20:44

from django.db import migrations, models
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_note_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=notes.models.upload_to, verbose_name='Превью'),
        ),
    ]
