# Generated by Django 4.0.6 on 2022-07-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='category',
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ManyToManyField(related_name='category', to='notes.category', verbose_name='Категория'),
        ),
    ]
